services:
  mysql:
    image: mysql
    container_name: mysql_MasterUuid
    restart: always
    ports:
      - "7001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    volumes:
      - planning-mysql-data:/var/lib/mysql

  container:
    image: planning/planning:latest
    container_name: planning-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7272:7272"

volumes:
  planning-mysql-data: